const Head = () => (
  <>
    <title>Solflare</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Generated by create next app" name="description" />
    <link href="/favicon.ico" rel="icon" />
  </>
);

export default Head;
